In [94]:
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt
import seaborn as sns

from scipy import stats

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [76]:
df = pd.read_excel('../data/raw/ALF_Data.xlsx')
df.head()

,Age,Gender,Region,Weight,Height,Body Mass Index,Obesity,Waist,Maximum Blood Pressure,Minimum Blood Pressure,Good Cholesterol,Bad Cholesterol,Total Cholesterol,Dyslipidemia,PVD,Physical Activity,Education,Unmarried,Income,Source of Care,PoorVision,Alcohol Consumption,HyperTension,Family HyperTension,Diabetes,Family Diabetes,Hepatitis,Family Hepatitis,Chronic Fatigue,ALF
0,65,M,east,56.0,162.1,21.31,0.0,83.6,135.0,71.0,48.0,249.0,297.0,0,0,3.0,0.0,0.0,1.0,Governament Hospital,0.0,1,0.0,0,0.0,1,1.0,0.0,0.0,0.0
1,36,M,south,60.2,162.2,22.88,0.0,76.6,96.0,52.0,31.0,135.0,166.0,0,0,3.0,0.0,NaN,1.0,Never Counsulted,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0
2,66,M,east,83.9,162.5,31.77,1.0,113.2,115.0,57.0,44.0,211.0,255.0,1,0,1.0,0.0,1.0,0.0,Never Counsulted,0.0,1,0.0,0,1.0,0,0.0,0.0,0.0,0.0
3,54,M,east,69.4,160.5,26.94,0.0,77.9,110.0,57.0,74.0,156.0,230.0,0,0,2.0,1.0,0.0,0.0,Private Hospital,0.0,1,0.0,0,0.0,0,0.0,0.0,0.0,0.0
4,63,M,north,73.1,159.2,28.84,0.0,89.3,132.0,73.0,67.0,154.0,221.0,0,0,1.0,0.0,0.0,NaN,clinic,0.0,0,1.0,0,0.0,0,0.0,0.0,0.0,0.0

In [93]:
df.describe()

,Age,Weight,Height,Obesity,Waist,Maximum Blood Pressure,Minimum Blood Pressure,Good Cholesterol,Bad Cholesterol,Dyslipidemia,PVD,Physical Activity,Education,Unmarried,Income,PoorVision,Alcohol Consumption,HyperTension,Family HyperTension,Diabetes,Family Diabetes,Hepatitis,Family Hepatitis,Chronic Fatigue,ALF
count,8.785000e+03,8.785000e+03,8.785000e+03,8495.000000,8.785000e+03,8.785000e+03,8.785000e+03,8.785000e+03,8.785000e+03,8785.000000,8785.000000,8775.000000,8765.000000,8333.000000,7624.000000,8222.000000,8785.000000,8705.000000,8785.000000,8783.000000,8785.000000,8763.00000,8779.000000,8750.000000,6000.000000
mean,-2.834386e-16,2.182407e-15,-3.891253e-15,0.315951,-3.084967e-15,-6.203745e-14,-3.083981e-16,7.560891e-16,-1.330246e-16,0.105407,0.039271,2.028490,0.431603,0.368655,0.417366,0.063610,0.304041,0.402412,0.233238,0.111351,0.311781,0.06653,0.020503,0.029029,0.077333
std,1.000057e+00,1.000057e+00,1.000057e+00,0.464921,1.000057e+00,1.000057e+00,1.000057e+00,1.000057e+00,1.000057e+00,0.307095,0.194251,0.815207,0.495328,0.482469,0.493157,0.244071,0.460026,0.490412,0.422917,0.314585,0.463247,0.24922,0.141723,0.167896,0.267142
min,-1.797292e+00,-5.189303e+00,-3.964744e+00,0.000000,-3.256514e+00,-4.907524e+00,-3.946034e+00,-6.882226e+00,-4.770189e+00,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,-8.346331e-01,-6.625588e-01,-7.033565e-01,0.000000,-6.661183e-01,-6.327524e-01,-6.374786e-01,-6.419118e-01,-6.529989e-01,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
50%,-1.420464e-02,4.200363e-02,7.973300e-03,0.000000,7.778593e-02,2.389908e-02,-3.602181e-02,-2.672298e-02,1.252619e-02,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
75%,8.595862e-01,6.452475e-01,7.085800e-01,1.000000,6.463877e-01,6.528744e-01,5.884757e-01,6.577451e-01,6.433610e-01,0.000000,0.000000,2.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000
max,1.683564e+00,3.642335e+00,3.125006e+00,1.000000,3.883159e+00,3.013190e+00,5.639966e+00,3.764898e+00,6.894902e+00,1.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000

Next, we will keep only those records for which we have the non-null value of the response variable i.e. ALF.

In [77]:
data_train = df[(df['ALF'].notnull())]

Let's separate the continuous and categorical variables for better understanding.

In [78]:
continuous_cols = ['Age', 'Weight','Height','Body Mass Index', 'Waist', 'Maximum Blood Pressure', 'Minimum Blood Pressure', 
                   'Good Cholesterol','Bad Cholesterol', 'Total Cholesterol']
categorical_cols = list(set(df.columns)-set(continuous_cols))

We will now replace the empty values in the continuous features with the mean of that particular feature column.

In [79]:
df.head()
for col in continuous_cols:
    df[col].fillna(df[col].mean(), inplace=True)

,Age,Gender,Region,Weight,Height,Body Mass Index,Obesity,Waist,Maximum Blood Pressure,Minimum Blood Pressure,Good Cholesterol,Bad Cholesterol,Total Cholesterol,Dyslipidemia,PVD,Physical Activity,Education,Unmarried,Income,Source of Care,PoorVision,Alcohol Consumption,HyperTension,Family HyperTension,Diabetes,Family Diabetes,Hepatitis,Family Hepatitis,Chronic Fatigue,ALF
0,65,M,east,56.0,162.1,21.31,0.0,83.6,135.0,71.0,48.0,249.0,297.0,0,0,3.0,0.0,0.0,1.0,Governament Hospital,0.0,1,0.0,0,0.0,1,1.0,0.0,0.0,0.0
1,36,M,south,60.2,162.2,22.88,0.0,76.6,96.0,52.0,31.0,135.0,166.0,0,0,3.0,0.0,NaN,1.0,Never Counsulted,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0
2,66,M,east,83.9,162.5,31.77,1.0,113.2,115.0,57.0,44.0,211.0,255.0,1,0,1.0,0.0,1.0,0.0,Never Counsulted,0.0,1,0.0,0,1.0,0,0.0,0.0,0.0,0.0
3,54,M,east,69.4,160.5,26.94,0.0,77.9,110.0,57.0,74.0,156.0,230.0,0,0,2.0,1.0,0.0,0.0,Private Hospital,0.0,1,0.0,0,0.0,0,0.0,0.0,0.0,0.0
4,63,M,north,73.1,159.2,28.84,0.0,89.3,132.0,73.0,67.0,154.0,221.0,0,0,1.0,0.0,0.0,NaN,clinic,0.0,0,1.0,0,0.0,0,0.0,0.0,0.0,0.0

In [80]:
# All continuous columns without the age
continuous_cols_1 = ['Weight','Height','Body Mass Index', 'Waist', 'Maximum Blood Pressure', 'Minimum Blood Pressure', 
                   'Good Cholesterol','Bad Cholesterol', 'Total Cholesterol']

We will calculate the normality of the continuous features by checking the skewness and kurtosis values.

In [81]:
for col in continuous_cols_1:
    print(col + ': Kurt -->',"{0:.4f}".format(df[col].kurt()))

Weight: Kurt --> 1.9671
Height: Kurt --> -0.2364
Body Mass Index: Kurt --> 2.6014
Waist: Kurt --> 0.6306
Maximum Blood Pressure: Kurt --> 1.4730
Minimum Blood Pressure: Kurt --> 1.5965
Good Cholesterol: Kurt --> 1.5935
Bad Cholesterol: Kurt --> 5.6960
Total Cholesterol: Kurt --> 5.3359

In [82]:
for col in continuous_cols_1:
    print(col + ': Skewness --> ',"{0:.4f}".format(df[col].skew()))

Weight: Skewness -->  0.9831
Height: Skewness -->  0.1088
Body Mass Index: Skewness -->  1.1628
Waist: Skewness -->  0.4998
Maximum Blood Pressure: Skewness -->  1.0518
Minimum Blood Pressure: Skewness -->  -0.2782
Good Cholesterol: Skewness -->  1.0203
Bad Cholesterol: Skewness -->  1.0292
Total Cholesterol: Skewness -->  0.9554

In [63]:
#PCA Analysis
#OneHotEncoding
#Scale Data

It has been found that the features are a little skewed and to remove the skewness and make them normal we will apply the box-cox transformation. <br><br>
Also, we have some correlated features such as BMI and Total Cholesterol. We will get rid of these features as well.

In [83]:
continuous_cols_2 = [ 'Age', 'Weight','Height','Waist', 'Maximum Blood Pressure', 'Minimum Blood Pressure', 
                   'Good Cholesterol','Bad Cholesterol']

for col in continuous_cols_2:
    nd = np.asarray(df[col].values)
    dft = stats.boxcox(nd)[0]
    df[col] = dft.tolist()

df.drop(columns = ['Body Mass Index', 'Total Cholesterol'], inplace=True)
df.head()

,Age,Gender,Region,Weight,Height,Obesity,Waist,Maximum Blood Pressure,Minimum Blood Pressure,Good Cholesterol,Bad Cholesterol,Dyslipidemia,PVD,Physical Activity,Education,Unmarried,Income,Source of Care,PoorVision,Alcohol Consumption,HyperTension,Family HyperTension,Diabetes,Family Diabetes,Hepatitis,Family Hepatitis,Chronic Fatigue,ALF
0,12.071210,M,east,2.843350,12.187289,0.0,4.209662,0.855827,278.909932,3.151536,13.973865,0,0,3.0,0.0,0.0,1.0,Governament Hospital,0.0,1,0.0,0,0.0,1,1.0,0.0,0.0,0.0
1,8.774131,M,south,2.877600,12.190196,0.0,4.130545,0.854444,180.059513,2.859137,11.090122,0,0,3.0,0.0,NaN,1.0,Never Counsulted,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0
2,12.168353,M,east,3.029090,12.198910,1.0,4.482682,0.855244,204.865234,3.094462,13.141364,1,0,1.0,0.0,1.0,0.0,Never Counsulted,0.0,1,0.0,0,1.0,0,0.0,0.0,0.0,0.0
3,10.942455,M,east,2.943635,12.140602,0.0,4.145783,0.855063,204.865234,3.427478,11.724657,0,0,2.0,1.0,0.0,0.0,Private Hospital,0.0,1,0.0,0,0.0,0,0.0,0.0,0.0,0.0
4,11.874394,M,north,2.967326,12.102430,0.0,4.269233,0.855752,290.004063,3.365289,11.666913,0,0,1.0,0.0,0.0,NaN,clinic,0.0,0,1.0,0,0.0,0,0.0,0.0,0.0,0.0

For fetching accurate results through our model, we need to scale the feature data.

In [84]:
# Scaling
df[continuous_cols_2] = StandardScaler().fit_transform(df[continuous_cols_2])
df.head()

,Age,Gender,Region,Weight,Height,Obesity,Waist,Maximum Blood Pressure,Minimum Blood Pressure,Good Cholesterol,Bad Cholesterol,Dyslipidemia,PVD,Physical Activity,Education,Unmarried,Income,Source of Care,PoorVision,Alcohol Consumption,HyperTension,Family HyperTension,Diabetes,Family Diabetes,Hepatitis,Family Hepatitis,Chronic Fatigue,ALF
0,0.859586,M,east,-1.375619,-0.477502,0.0,-0.891051,0.609135,-0.078224,-0.097270,1.993208,0,0,3.0,0.0,0.0,1.0,Governament Hospital,0.0,1,0.0,0,0.0,1,1.0,0.0,0.0,0.0
1,-0.644516,M,south,-1.050205,-0.467287,0.0,-1.468656,-1.882007,-1.539388,-1.631512,-0.334656,0,0,3.0,0.0,NaN,1.0,Never Counsulted,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0
2,0.903902,M,east,0.389124,-0.436667,1.0,1.102177,-0.440167,-1.172720,-0.396743,1.321183,1,0,1.0,0.0,1.0,0.0,Never Counsulted,0.0,1,0.0,0,1.0,0,0.0,0.0,0.0,0.0
3,0.344657,M,east,-0.422791,-0.641547,0.0,-1.357408,-0.767470,-1.172720,1.350621,0.177565,0,0,2.0,1.0,0.0,0.0,Private Hospital,0.0,1,0.0,0,0.0,0,0.0,0.0,0.0,0.0
4,0.769800,M,north,-0.197701,-0.775672,0.0,-0.456144,0.473608,0.085765,1.024309,0.130951,0,0,1.0,0.0,0.0,NaN,clinic,0.0,0,1.0,0,0.0,0,0.0,0.0,0.0,0.0

In [85]:
df[continuous_cols_2].skew()

Age                      -0.068768
Weight                   -0.002983
Height                   -0.001338
Waist                    -0.000054
Maximum Blood Pressure    0.001732
Minimum Blood Pressure    0.104012
Good Cholesterol         -0.001995
Bad Cholesterol           0.020944
dtype: float64

In [86]:
df[continuous_cols_2].kurt()

Age                      -1.122800
Weight                    0.210924
Height                   -0.223052
Waist                     0.046399
Maximum Blood Pressure    0.057958
Minimum Blood Pressure    1.273471
Good Cholesterol          0.215842
Bad Cholesterol           0.834879
dtype: float64

Now, let's perform some analysis on the catergorical features. Firstly, we will convert the categories into the nominal data as integers and for each missing value we will create a new category with value as -1.

In [87]:
#Categorical

name_category = ['Gender', 'Region', 'Source of Care']

df.loc[(df.Gender == 'M'),'Gender']=1
df.loc[(df.Gender == 'F'),'Gender']=0
#0=F, 1=M

df.loc[(df.Region == 'east'),'Region']=1
df.loc[(df.Region == 'west'),'Region']=0
df.loc[(df.Region == 'north'),'Region']=2
df.loc[(df.Region == 'south'),'Region']=3

#0=West, 1=East, 2=North, 3=South


df.loc[(df['Source of Care'] == 'Governament Hospital'),'Source of Care']=1
df.loc[(df['Source of Care'] == 'Private Hospital'),'Source of Care']=0
df.loc[(df['Source of Care'] == 'clinic'),'Source of Care']=2
df.loc[(df['Source of Care'] == 'Never Counsulted'),'Source of Care']=3


df['Source of Care']

0       1
1       3
2       3
3       0
4       2
       ..
8780    0
8781    0
8782    0
8783    2
8784    2
Name: Source of Care, Length: 8785, dtype: object

In [88]:
df.where(df[categorical_cols].isna(), -1)

,Age,Gender,Region,Weight,Height,Obesity,Waist,Maximum Blood Pressure,Minimum Blood Pressure,Good Cholesterol,Bad Cholesterol,Dyslipidemia,PVD,Physical Activity,Education,Unmarried,Income,Source of Care,PoorVision,Alcohol Consumption,HyperTension,Family HyperTension,Diabetes,Family Diabetes,Hepatitis,Family Hepatitis,Chronic Fatigue,ALF
0,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0
1,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,NaN,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0
2,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0
3,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0
4,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,-1.0,NaN,-1,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8780,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,NaN,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,NaN
8781,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,NaN
8782,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,NaN
8783,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,NaN
8784,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1.0,-1.0,-1.0,-1,NaN,-1,-1.0,-1,-1.0,-1,-1.0,-1.0,-1.0,NaN

In [89]:
df[categorical_cols].fillna(-1, inplace=True)

C:\Users\rahul\Anaconda3\lib\site-packages\pandas\core\frame.py:4153: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

In [90]:
df[categorical_cols]

,Physical Activity,Unmarried,Family Hepatitis,Source of Care,Chronic Fatigue,Gender,Family HyperTension,PoorVision,Hepatitis,Income,PVD,HyperTension,Family Diabetes,Region,Obesity,Alcohol Consumption,Education,Diabetes,ALF,Dyslipidemia
0,3.0,0.0,0.0,1,0.0,1,0,0.0,1.0,1.0,0,0.0,1,1,0.0,1,0.0,0.0,0.0,0
1,3.0,NaN,0.0,3,0.0,1,0,0.0,0.0,1.0,0,0.0,0,3,0.0,0,0.0,0.0,0.0,0
2,1.0,1.0,0.0,3,0.0,1,0,0.0,0.0,0.0,0,0.0,0,1,1.0,1,0.0,1.0,0.0,1
3,2.0,0.0,0.0,0,0.0,1,0,0.0,0.0,0.0,0,0.0,0,1,0.0,1,1.0,0.0,0.0,0
4,1.0,0.0,0.0,2,0.0,1,0,0.0,0.0,NaN,0,1.0,0,2,0.0,0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8780,3.0,NaN,0.0,0,0.0,0,1,0.0,0.0,0.0,0,0.0,1,1,0.0,1,0.0,0.0,NaN,0
8781,2.0,0.0,0.0,0,0.0,0,0,0.0,0.0,1.0,1,1.0,1,2,1.0,0,0.0,0.0,NaN,0
8782,3.0,0.0,0.0,0,0.0,0,0,0.0,0.0,0.0,0,1.0,0,3,0.0,0,0.0,0.0,NaN,0
8783,2.0,0.0,0.0,2,0.0,0,0,0.0,0.0,1.0,0,0.0,0,1,0.0,0,1.0,0.0,NaN,0
8784,1.0,0.0,0.0,2,0.0,1,1,NaN,0.0,0.0,0,1.0,0,1,0.0,0,0.0,0.0,NaN,0

In [91]:
df[categorical_cols] = df[categorical_cols].astype(int, errors='ignore')

Finally, we will save our preprocessed data into a new CSV file which we will use in the modeling notebook.

In [92]:
df.to_csv('../data/processed//cleaned_ALF.csv')